Repository c3pm-labs/c3pm, pull requests merged in 2020-12, with the labels that each got.

#17 add: support for development and production environments
  api/api.go
  ctpm/add.go
  env/dev.go
  env/prod.go
Labels: enhancement

#21 add: License.txt file with an MIT license
  LICENSE.txt
Labels: documentation

#19 fix(add): support package with a dash in the name
  ctpm/add.go
Labels: bug
